source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DLinkSDK/deeplink-dev-specs.git'

platform :ios, '15.0'

target 'AppAttributionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppAttributionDemo
  pod 'AppAttribution', '~>3.1.0'
  # [Optional] if you want to support GoogleAdsOnDeviceConversion
  pod 'AppAttribution_GoogleAdsOnDevice', '~>3.1.0'
  
  pod 'AppsFlyerFramework', '6.12.1'
  
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end

end
